### ISSUE TITLE
Crash when updating past version 0.4.2

### ISSUE THREAD

**Issue by mcclellanja** [hlysine/create_connected#34]
I have tried all of the versions 0.5.0 to 0.6.1 and they all give me this same crash. Here is the crash report where it mentions that it might be create connected. Let me know if you need the whole report.

`A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mods: 
	Create (create), Version: 0.5.1.f
		Issue tracker URL: https://github.com/Creators-of-Create/Create/issues
		at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.schematics.client.ClientSchematicLoader.cc$searchInSubfolder(ClientSchematicLoader.java:536)

	Create: Connected (create_connected), Version: 0.6.0-mc1.20.1
		Issue tracker URL: https://github.com/hlysine/create_connected/issues
		Mixin class: com.hlysine.create_connected.mixin.nestedschematics.ClientSchematicLoaderMixin
		Target: com.simibubi.create.content.schematics.client.ClientSchematicLoader
		at TRANSFORMER/create@0.5.1.f/com.simibubi.create.content.schematics.client.ClientSchematicLoader.cc$searchInSubfolder(ClientSchematicLoader.java:536)
Stacktrace:
	at com.simibubi.create.content.schematics.client.ClientSchematicLoader.cc$searchInSubfolder(ClientSchematicLoader.java:536) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create_connected.mixins.json:nestedschematics.ClientSchematicLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
-- MOD create --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at com.simibubi.create.Create.lambda$onCtor$1(Create.java:148) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:classloading,re:mixin}
		at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.20.1-47.2.19.jar%23231!/:?] {}
		at com.simibubi.create.Create.onCtor(Create.java:148) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:classloading,re:mixin}
		at com.simibubi.create.Create.<init>(Create.java:93) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:classloading,re:mixin}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.19.jar%23232!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.19.jar%23231!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/mccle/curseforge/minecraft/Instances/Create Tester/mods/create-1.20.1-0.5.1.f.jar
	Failure message: Create (create) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 0.5.1.f
	Mod Issue URL: https://github.com/Creators-of-Create/Create/issues
	Exception message: java.lang.NullPointerException: Cannot invoke "com.hlysine.create_connected.config.CServer.schematicsNestingDepth()" because the return value of "com.hlysine.create_connected.config.CCConfigs.server()" is null
Stacktrace:
	at com.simibubi.create.content.schematics.client.ClientSchematicLoader.cc$searchInSubfolder(ClientSchematicLoader.java:536) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create_connected.mixins.json:nestedschematics.ClientSchematicLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.schematics.client.ClientSchematicLoader.handler$cfe000$cc$refresh(ClientSchematicLoader.java:530) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create_connected.mixins.json:nestedschematics.ClientSchematicLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.schematics.client.ClientSchematicLoader.refresh(ClientSchematicLoader.java:148) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create_connected.mixins.json:nestedschematics.ClientSchematicLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.simibubi.create.content.schematics.client.ClientSchematicLoader.<init>(ClientSchematicLoader.java:43) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:create_connected.mixins.json:nestedschematics.ClientSchematicLoaderMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at com.simibubi.create.CreateClient.<clinit>(CreateClient.java:49) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:classloading}
	at com.simibubi.create.Create.lambda$onCtor$1(Create.java:148) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:classloading,re:mixin}
	at net.minecraftforge.fml.DistExecutor.unsafeRunWhenOn(DistExecutor.java:111) ~[fmlcore-1.20.1-47.2.19.jar%23231!/:?] {}
	at com.simibubi.create.Create.onCtor(Create.java:148) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:classloading,re:mixin}
	at com.simibubi.create.Create.<init>(Create.java:93) ~[create-1.20.1-0.5.1.f.jar%23201!/:0.5.1.f] {re:classloading,re:mixin}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.2.19.jar%23232!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.2.19.jar%23231!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}'

**Comment by hlysine** [comment]
Something in your setup is affecting the load order, causing the schematics classes to be loaded before configs are registered. I've added additional safety checks in this dev version. Please test if this version solves your issue.

[UNZIP ME create_connected-0.6.1-dev-mc1.20.1-all.zip](https://github.com/hlysine/create_connected/files/14060951/UNZIP.ME.create_connected-0.6.1-dev-mc1.20.1-all.zip)

**Comment by mcclellanja** [comment]
That did the trick! Thanks for the quick response that was impressive!
