### ISSUE TITLE
[1.20.1] - v0.7.2 - Crash with Create: Dreams & Desires & Copycats+ installed

### ISSUE THREAD

**Issue by Razsiel** [hlysine/create_connected#48]
Despite having seen the comments on [issue #6](https://github.com/copycats-plus/copycats/issues/6) on the Copycats+ repo, it seems the 1.20.1 version still causes issues when trying to load a world. Hangs at 100% and then crashes. Had previously only Create: Connected installed and updated recently and added CopyCats+. Have tried either mod on their own and works, but together still crashes. Mod downloaded from curseforge and modrinth to see if there was a difference.

[latest.log](https://github.com/hlysine/create_connected/files/14313021/latest.log)
[crash-2024-02-16_16.36.44-server.txt](https://github.com/hlysine/create_connected/files/14313023/crash-2024-02-16_16.36.44-server.txt)

`net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:897) ~[client-1.20.1-20230612.114412-srg.jar%23576!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23576!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23576!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23576!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23576!/:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Cannot set property DirectionProperty{name=facing, clazz=class net.minecraft.core.Direction, values=[north, east, south, west, up, down]} as it does not exist in Block{copycats:copycat_slab}
	at net.minecraft.world.level.block.state.StateHolder.m_61124_(StateHolder.java:122) ~[client-1.20.1-20230612.114412-srg.jar%23576!/:?]
	at com.hlysine.create_connected.compat.CopycatsManager.copyProperty(CopycatsManager.java:72) ~[create_connected-0.7.2-mc1.20.1-all.jar%23422!/:0.7.2-mc1.20.1]
	at com.hlysine.create_connected.compat.CopycatsManager.convert(CopycatsManager.java:66) ~[create_connected-0.7.2-mc1.20.1-all.jar%23422!/:0.7.2-mc1.20.1]
	...`

**Comment by Razsiel** [comment]
Having created a new modpack and going through almost every single mod that I could reasonably think would mess with block placing or rendering them in a non-vanilla way (drawers, backpacks, minimap for instance), I tried loading a new world with all the mods enabled and that worked, so it's related to something in my current save. Am investigating what it could be and will report back here when found!

**Comment by Razsiel** [comment]
@hlysine Identified the culprit! Create Dreams'n'Desires' Copycat slab.
For some reason (don't have a debugging setup, deducing this through reading the crash log + reading through code of C:C & C:DnD, suspecting a false-positive name/blockstate in a conditional) the [CopycatsManager](src/main/java/com/hlysine/create_connected/compat/CopycatsManager.java) is picking up the slab added by DnD, which has the `facing` property [](https://github.com/LopyLuna/Create-Dreams-and-Desires/blob/064209d9d898a8a9a1c8b768021eb8e2393c6cbf/src/main/java/uwu/lopyluna/create_dd/block/BlockProperties/copycat/BlockcopycatSlab.java#L43)

Reproduction:

Installed mods:
- Create 0.5.1f
- Create Connected 0.7.2
- Create Dreams-n-Desires 0.2c.PREBETA
- Create Copycats+ 1.1.0

Steps:
- Load with create, connected and dnd enabled.
- Create a new world
- Place copycat slabs from both mods (I dit it in multiple orientation and filled with 2 types of blocks; log and a connected block like casings)
- Save, exit, close.
- Enable Copycats+ and start game.
- Open world: *Crash*

**Comment by hlysine** [comment]
Ah I see! Thank you so much for the testing work. I think I have heard similar reports about DnD in Copycats+ discord, but you are the first to find the root cause 👍 

Here's a dev version that should hopefully fix the issue: [UNZIP ME create_connected-0.7.2-mc1.20.1-dev-all.zip](https://github.com/hlysine/create_connected/files/14322824/UNZIP.ME.create_connected-0.7.2-mc1.20.1-dev-all.zip)

**Comment by Razsiel** [comment]
New jar works in my world with all mods enabled! Thanks for the fast fix and openness!
